server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}
  # CORS network error (URL scheme must be "http" or "https" for CORS request) solution.
  # Ref: https://stackoverflow.com/a/73376127
  forward-headers-strategy: framework

app:
  secret: ${APP_SECRET:c04nKbDFfJ2v0XSRtNKHQQq5Km3zMSZxla7paMSUzBOI/ORhgnTC7eJrqqEZQGKm}
spring:
  application:
    name: ${APP_NAME:DEV-UniHome}
    description: ${APP_DESCRIPTION:Profile de DEV}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:29190/railway
    username: postgres
    password: KQzAkxQucQqXtwpSfUjBomtjDKAuNVHo
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:test@email.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: ${MAIL_SSL:false}
          tls:
            enable: ${MAIL_TLS:false}
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

management:
  metrics:
    enable:
      process.cpu: false
      system.cpu: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: false