name: Build do projeto
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev
jobs:
  build:
    name: Build do backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Maven
        run: |
          sudo apt install maven

      - name: Clean package
        run: mvn clean package -DskipTests